version: '3'

services:
  master:
    build: master
    image: salt-master-debug:50313
    container_name: salt-50313-master
    ports:
      - "4505:4505"
      - "4506:4506"
    links:
      - repo:repo
  minion:
    build: minion
    image: salt-minion-debug:50313
    links:
      - master:salt
      - repo:repo
    entrypoint:
      - salt-minion
      - --log-level
      - debug
  repo:
    build: repo
