version: '3'

services:
  master:
    build: master
    image: salt-master-debug:50313
    ports:
      - "4505:4505"
      - "4506:4506"
  minion:
    build: minion
    image: salt-minion-debug:50313
    links:
      - master:salt
    entrypoint:
      - salt-minion
      - --log-level
      - debug
